name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Build the project
      - name: Build the project
        run: cargo build --release

      # Upload the binary as an artifact, correctly naming it based on platform
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-binary
          path: |
            target/release/runlike${{ matrix.platform == 'windows-latest' && '.exe' || '' }}
