name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy

      - name: Run tests
        run: cargo test --verbose
